API_TOKEN = "8686620867:AAHmSBZUww3ySTfLA40bpM0Bs_3r1-7pSMg"
CHAT_ID = "1969573200"
GEMINI_API_KEY = ""

SYMBOLS = [
    "BTC/USDT",
    "ETH/USDT",
    "SOL/USDT",
    "BNB/USDT",
    "XRP/USDT",
    "ADA/USDT",
    "DOGE/USDT",
    "LINK/USDT",
    "LTC/USDT",
    "S/USDT",
    "SUI/USDT",
    "SUI/USDT",
    "XAU/USDT",
    "AVAX/USDT"
]

TIMEFRAME_1H = "1h"
TIMEFRAME_15M = "15m"